# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_info": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dotel-saramsz.github.io/basic_nbdev/"

git_url = "https://github.com/dotel-saramsz/basic_nbdev/tree/master/"

def custom_doc_links(name): return None
