# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_info', 'DemoClass']

# Cell

def print_info(about):
    info = f'You just type {about} from your own keyboard'
    return info

# Cell
class DemoClass:
    def __init__(self, name):
        self.name = name
    def show(self):
        print(self.name)