# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_info']

# Cell

def print_info(about):
    info = f'You just type {about} from your keyboard'
    return info